### ISSUE TITLE
Code Distribution

### ISSUE THREAD

**Issue by phase** [Dimensions/Dimensions#1]
Do we want to have Diff patches for the Minecraft source? Or do we want to upload the modified code?

People would have to run a shell script in order to patch it, but we could also make it more user friendly. With the code, people would have to know how to open the `.jar` and put files into it.

**Comment by phase** [comment]
Oh wait, to do patches, people would have to have the Minecraft source... I think we could just use MCP and get the modified code form there.

**Comment by phase** [comment]
We could leave all the original code in a separate package and call methods from it in the NMS. This would make it easy to distribute, and easy to code.

**Comment by phase** [comment]
But then there would be no good way for people to help with the NMS implementation. Do we want to include the Minecraft source? Is that legal?

**Comment by phase** [comment]
We could have 2 repos, one with the modified NMS source, one with the original code. But then people would need to download both, and it gets complicated....

**Comment by phase** [comment]
Since Mojang doesn't allow us to distribute the decompiled source of minecraft, we can only open source the indirect implementation.

**Comment by phase** [comment]
There are going to be two parts, the _indirect implementation_ and the _direct implementation_. The _indirect_ will be the open Java source code, while the _direct_ will be Diff patches to NMS. There will be scripts for you to run which will make the process a lot easier.

**Comment by phase** [comment]
Here's our hierarchy:

Dimensions/
- indirect/
  - Java source code...
- direct/
  - Diff Patches...
- mcp/
  - Untracked MCP Stuff...

The MCP files won't be on GitHub, as that'd be open sourcing Minecraft.

**Comment by phase** [comment]
Using the described methods above, we are distributing the code in two ways, _indirect_ and _direct_. You can read the CONTRIBUTING.md file for more information.

**Comment by wgaylord** [comment]
Just to chime in here a program I am currently working on could make it so that your code could run with out having to decompiling and patch the code then recompile. (it will slow loading time for the first load but... (It will cache the old files to speed that up.))  Right now my program is mostly stub classes as I started a recode of it but if you are interested https://github.com/chibill/DeObfuscating-Loader

**Comment by phase** [comment]
@chibill I like the idea of using MCP to recompile it, as we can distribute the changed code easily. Plus you only have to decompile once.

**Comment by wgaylord** [comment]
I see. I was mostly talking about for when you are ready to start distributing. (So unlike current Spigot stuff you don't have the user manually compile it with tools. Well I am not sure if you would have to do that but..  Yeah..)

**Comment by phase** [comment]
@chibill We manually compile the tools and host them on the website (once it's done). Then all people have to do is drag and drop them into their vanilla jar.

**Comment by wgaylord** [comment]
Okay. That seems a lot easier then if you use my loader. Ether way I could use your project to test out my loader later as it is in the right type of set up and it would be a good test.

**Comment by wgaylord** [comment]
Also not sure if this would be here but we can tell MCP to only decompile the server. That way we don't have client classes in our way as we dev. using --server as the args for decompile.sh

Edit:
Also we need a better way of talking about this stuff...

**Comment by wgaylord** [comment]
@phase Also would we be safe to have this closed? As I think we finally figure it out right?

**Comment by phase** [comment]
@chibill I was roaming around on GitHub and found @minecrell's VanillaGradle plugin: https://github.com/Minecrell/VanillaGradle/issues/1 Can we use that?

**Comment by wgaylord** [comment]
Maybe I will look into it.

Edit:
Well it does not seem to use any patch system. And also it uses forge to deobf and decompile the jar. 

But we can edit it to our need.

**Comment by wgaylord** [comment]
https://github.com/nailed/mcp Looks be more what we need. And we can set it up to build the patches with a small amount of code.

Edit: 
Actually we can just use there plugin and make out own to do the patching and anything else needed. (As plugins just add more tasks.)

Edit2:
Or this https://github.com/AbrarSyed/GMCP

**Comment by phase** [comment]
@chibill https://github.com/nailed/mcp was recently updated, so we should use that.

**Comment by wgaylord** [comment]
Still have to make the patching part but. (Simple I think.)
Edit: Also do you want me to implement that and do a push later? (After i make the patcher plugin.)

**Comment by iLexiconn** [comment]
Reflection?

**Comment by wgaylord** [comment]
? We never said anything about reflection. (I don't think.)

**Comment by iLexiconn** [comment]
I know, but maybe we could use it instead of patches

**Comment by wgaylord** [comment]
Why? Reflection is slow (at times) and also we can't add in code if we need to.

**Comment by phase** [comment]
Reflection is definitely the wrong way to go. The whole reason we need patches to because we want to add code. We _could_ use Sponge's Mixin, which modifies the methods' bytecode at runtime. Patches would be the best option though, as they're easier to implement and understand.

**Comment by wgaylord** [comment]
And we would have to use the launchwraper if we used the mix-in system.

**Comment by phase** [comment]
Hrm... I think I have an idea on how we can use `git diff`..

We `git init` the `mcp/src/old_nms/`, and then compare that with the new folder.

**Comment by wgaylord** [comment]
But why? That's just adding more steps that could go wrong (I think.) Also we should find a way to communicate that is not through issues.

**Comment by phase** [comment]
We initialize the `old_nms` and `minecraft_server`. then we can compare them using `git diff`, which would solve the problem of it only going in one file, as there would be a file per commit. This would eliminate the need for a Gradle plugin, as we only needed it for the patches.

**Comment by phase** [comment]
I think we've got distribution down.
