### ISSUE TITLE
Make dim init actually work.

### ISSUE THREAD

**Issue by wgaylord** [Dimensions/Dimensions#10]
dim init is still erroring for me. I am not sure if its on my end or what..

Decompiling NMS...
c:\python27\python.exe: can't open file 'runtime/decompile.py': [Errno 2] No suc
h file or directory
Initilaizing the Dimensions server...
Making a local copy of the NMS source...
cp: cannot stat `mcp/src/minecraft_server/net/': No such file or directory
Setting up Solar...
Moving Solar into NMS...
Copying indirect code into NMS...
Initializing NMS...
./dim.sh: line 60: cd: mcp/src/minecraft_server/net/: No such file or directory
Reinitialized existing Git repository in c:/Users/bill/documents/github/Dimensio
ns/.git/
fatal: A branch named 'dimensions' already exists.

> Updating Solar...
> fatal: Not a git repository (or any of the parent directories): .git
> Applying patches to MCP...
> cp: cannot stat `direct/': No such file or directory
> fatal: Not a git repository (or any of the parent directories): .git

**Comment by phase** [comment]
Is this still happenning with the new system?

**Comment by wgaylord** [comment]
As of https://github.com/Dimensions/Dimensions/commit/2a4e89fc4160b78f87aa69d08962ad250bf29759

it was that.

**Comment by phase** [comment]
@chibill According to the error, it looks like it's not putting MCP in the right folder. Are all the .bats & .shs in the `mcp/`?

**Comment by wgaylord** [comment]
Yes... simple fix but you need to move back into /mcp i nthe script and then call decompile.sh  decompile.sh uses local paths to see the .py files and also its internal python install. Testing a fix right now..

**Comment by phase** [comment]
@chibill: `Nope. :( Trying my fix really quick on my end.`

**Comment by wgaylord** [comment]
Fix is a comment on your commit.
Also don't forget to CD out of MCP after that.

**Comment by wgaylord** [comment]
I will fix it now. But it might look odd as I am on my tablet.

**Comment by phase** [comment]
If Python isn't installed, it gives an error. Is there any way we can automatically install Python?

**Comment by wgaylord** [comment]
If we can see if there on windows we can use mcp's internal python copy.

**Comment by wgaylord** [comment]
Or try using jython... When I get home I will look into it.

**Comment by phase** [comment]
Using Jython would be sweet!

**Comment by wgaylord** [comment]
Okay. Actually I can do that in about 10 minuetes after school. I will make it download jython into the MCP folder. (So we don't have the last problem again..) Then run decompile.py using jython.

**Comment by wgaylord** [comment]
Okay should work now with out a Python install. https://github.com/Dimensions/Dimensions/commit/ba17d816eee3f6201ecca49dce1b308c6dbf03a5 

Can't test that right now because I am still at school. And they don't have git bash.

Not going to close this till we confirm it works.

**Comment by phase** [comment]
You can put Git Bash on a flashdrive. :D

**Comment by wgaylord** [comment]
:) cool!

**Comment by wgaylord** [comment]
Well it work mostly.

**Comment by phase** [comment]
I kept getting an error with Jython saying it couldn't find the Java Version, but I was on a public computer. Is it working for you?

**Comment by wgaylord** [comment]
Yeah. I will test again later.

**Comment by phase** [comment]
Finally working!
