### ISSUE TITLE
Use forge gradle 2.0

### ISSUE THREAD

**Issue by Techcable** [Dimensions/Dimensions#13]
Will remove the silly nailed directories.

**Comment by phase** [comment]
If I remember correctly, there was some reason why we couldn't use it. I believe it had something to do with MCP.

Edit:
We're using a heavily modified version of Nailed to fit with Dimensions, soon we will put this on GitHub and change the directories to "Dimensions".

**Comment by phase** [comment]
Now we're using [Dim](https://github.com/dimensions/dim), so no need to use Forge's.
