### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by phase** [Dimensions/Dimensions#14]
We need to set up Travis. Does it need to use Gradle?

**Comment by wgaylord** [comment]
I can set up a Jenkins server. (Have one right now actually.)

**Comment by phase** [comment]
Travis is more accessible .

**Comment by wgaylord** [comment]
Okay.

**Comment by phase** [comment]
[Travis is working!](https://travis-ci.org/Dimensions/Dimensions/builds/)
