### ISSUE TITLE
Custom Launcher

### ISSUE THREAD

**Issue by phase** [Dimensions/Dimensions#15]
I'd like to make a custom launcher that shows the [Minecraft Tumbler](http://mcupdate.tumblr.com/) page like the normal launcher.

**Comment by wgaylord** [comment]
Why?  This is a server phase not a client....

**Comment by iLexiconn** [comment]
What @chibill said...

**Comment by phase** [comment]
Maybe not that, but some other news (about Dimensions) would be nice, alerting server owners that there is a new version out, ect.

**Comment by wgaylord** [comment]
We could just do an update checker like  craftbukkit had before.

**Comment by phase** [comment]
But that's boring... A custom launcher would be way cooler.

**Comment by wgaylord** [comment]
Maybe once deobfCraft is working... We can use an edited version of that....

**Comment by wgaylord** [comment]
Still don't see a point in this... Other than maybe making it so we only ship the launcher and it does the rest usi g github.

**Comment by phase** [comment]
dafuq

**Comment by iLexiconn** [comment]
nein

**Comment by phase** [comment]
no no no, let's wait until we have a team decision

**Comment by wgaylord** [comment]
The craziness was Waffie on a tablet..

**Comment by phase** [comment]
works fine for me :P
