### ISSUE TITLE
Setting up workspaces in IDEs

### ISSUE THREAD

**Issue by phase** [Dimensions/Dimensions#4]
All the source code is outputted into `mcp/src/minecraft_server/`, but we need a way to import it easily into IDEs. All of the libraries are in `mcp/jars/libraries/`. @slimshadeey1

**Comment by phase** [comment]
Here is what I had for Eclipse:

``` shell
mkdir -p mcp/eclipse/Server/src
cp -a mcp/src/minecraft_server/net mcp/eclipse/Server/src
cp -a mcp/src/minecraft_server/dimensions mcp/eclipse/Server/src
cp -a mcp/jars mcp/eclipse/Server

echo Files moved into eclipse/Server/
```

But this doesn't import the libraries.

**Comment by wgaylord** [comment]
You can copy an initial .classpath file and keep it in the repo and paste it in the eclipse folder of MCP maybe with the libaraies imported with relevant paths.

**Comment by phase** [comment]
@chibill I was having trouble with the libraries, Eclipse isn't loading them from the file that comes with MCP.

**Comment by wgaylord** [comment]
I don't really get what you mean. You mean even just trying to usE mcp's eclipse you don't get the libraries added?

**Comment by phase** [comment]
@chibill  Eclipse was yelling at me to import them, and when I did I check the file. The ones I had imported had direct paths to the jars (`C:/User/Desktop/dim/mcp/jar/libraries/...`), while the other ones had `/jar/libraries/...`

**Comment by wgaylord** [comment]
The relative paths are the ones the MCP ship with so it works in any location on your computer. So to make your libraries like that I think you have to manually edit the .classpath (Might be a better way..) EDIT: if it is in your project you can use just add jar in eclipse according to a answer on StackOverflow for relative paths.

**Comment by slimshadeey1** [comment]
if we use gradle, we can add the idea and eclipse plugin which generate the files automatically. Also we then add the gradle tasks to a script.

**Comment by wgaylord** [comment]
We can just use a shell script to make a .project and .classpath with the right values for the paths

**Comment by phase** [comment]
@chibill How do we get the full path using shell?

**Comment by phase** [comment]
```
echo "Moving files to the Eclipse folder..."
mkdir -p mcp/eclipse/Server/src
cp -a mcp/src/minecraft_server/net mcp/eclipse/Server/src
cp -a mcp/src/minecraft_server/dimensions mcp/eclipse/Server/src
cp -a mcp/jars mcp/eclipse/Server
```

**Comment by wgaylord** [comment]
I mean for Solar.  As well MCP makes Demensions .project and .classpath

**Comment by phase** [comment]
Here's something, just to give an idea.

``` shell
cd mcp/jars/

#Move files in subfolders to main folder
cd libraries
find . -mindepth 8 -type f -print -exec mv {} . \;

#Read paths of all the files
readfile gson-2.2.4.jar > libPath.txt
readfile guava-17.0.jar > libPath.txt
#for all of them
cd ..

#Go through libPath.txt and put all the paths into .classpath
```

**Comment by wgaylord** [comment]
yeah. and we for solar we can just have a .project file always in the solar repo as that does not really change. And a slightly edited version of that script to make its .classpath for deving it.

**Comment by wgaylord** [comment]
So now that we are trying to use gradle is this needed?

**Comment by phase** [comment]
@chibill Does it set up workspaces?

**Comment by wgaylord** [comment]
I believe so. iirc

**Comment by iLexiconn** [comment]
Yes it does

**Comment by phase** [comment]
@iLexiconn Can you write a tutorial on how to set it up in `CONTRIBUTING.md`?

**Comment by iLexiconn** [comment]
Sure thing

**Comment by iLexiconn** [comment]
Heh. Did you even look at it?

**Comment by phase** [comment]
@iLexiconn 

> Make changes to 'Nailed'
> Commit from the root folder

Any way we can change the name of this?

**Comment by iLexiconn** [comment]
Not yet.
