### ISSUE TITLE
Add Gradle

### ISSUE THREAD

**Issue by slimshadeey1** [Dimensions/Dimensions#5]
Add gradle and make a dimensions plugin for it. Easier to develop with.

**Comment by phase** [comment]
wut is gradle

**Comment by wgaylord** [comment]
https://gradle.org basicly a powerful Build script system. (Like Ant but a bit better.)

**Comment by phase** [comment]
And make a plugin using Diff4j to create the patches.

**Comment by wgaylord** [comment]
I can work on make us a plugin for gradle. Also we can use it for decompiling and all that so we only need mcp's mappings.

Also when I do make it we should give it its own Repo right?

**Comment by chibill** [comment]
Or we could modify this. https://github.com/AbrarSyed/GMCP

**Comment by phase** [comment]
@chibill Sure, I'll make one in a sec.

Edit:
https://github.com/Dimensions/DimGradle

**Comment by wgaylord** [comment]
Do you want it to also manage telling MCP to decompile it? And recompile + reobfuscate. Each can be its own task.

Edit:
Have not done anything with it yet.. (Have to finish homework (first dayvin the whole week with some))

**Comment by slimshadeey1** [comment]
check out minecraft forges gradle plugin as it already does the mcp decompiling. https://github.com/MinecraftForge/ForgeGradle

**Comment by wgaylord** [comment]
https://github.com/nailed/mcp does to with out installing forge.

**Comment by phase** [comment]
Not using Gradle!
