### ISSUE TITLE
Need artifact repo

### ISSUE THREAD

**Issue by slimshadeey1** [Dimensions/Dimensions#6]
We also need an artifact repo for development simplification

**Comment by wgaylord** [comment]
What do you mean?

**Comment by slimshadeey1** [comment]
We need a server hosting the bundled api and gradle plugin that people can import as maven repos.

**Comment by iLexiconn** [comment]
I can host the artifacts on https://ilexiconn.net/maven/
(Or http://jenkins.ilexiconn.net/)

**Comment by wgaylord** [comment]
Well if wee need a build server I got a jerkins server we can use. (I actually host it.)

**Comment by iLexiconn** [comment]
Okay :+1:

**Comment by phase** [comment]
We might just want to buy a domain & hosting.

**Comment by phase** [comment]
This will be hosted at https://github.com/dimensions/builds for the time being.
