### ISSUE TITLE
Add web Hooks/HTTP Requests

### ISSUE THREAD

**Issue by slimshadeey1** [Dimensions/Dimensions#7]
Add web hooks for events and also HTTP Get/Post Requests.

**Comment by wgaylord** [comment]
This just seems like a bad idea. It can open up doors to so many problems. And also attacks on a server...

**Comment by wgaylord** [comment]
Also we can go with the plan for other langagues and make it a plugin that at a later date if it is used a lot will be added into the core project.

**Comment by phase** [comment]
I don't see why we need something like this, the only connections that need to be made are between the client and the server.

**Comment by phase** [comment]
I don't think we need web hooks for anything since we don't have anything to hook into.
