### ISSUE TITLE
Move from using Issues for making decisions to something else.

### ISSUE THREAD

**Issue by wgaylord** [Dimensions/Dimensions#8]
So yeah we all have mostly been communicating using issues. I think we should find another way to communicate. My suggestion is to use slack.

**Comment by iLexiconn** [comment]
Skype group?

**Comment by wgaylord** [comment]
I don't have skype. (Well I do but I don't use it at all..) Also Slack is free and simple to set up. No installing and software to use it ether.

**Comment by iLexiconn** [comment]
Okay... How does it work? I have an account now ;)

**Comment by wgaylord** [comment]
Well I need to invite you I made a thing for our team. Which I am trying to figure out how you do with out having to send me your email.

**Comment by wgaylord** [comment]
Try join a team REMOVED

**Comment by iLexiconn** [comment]
https://dimensions-minecraft.slack.com/signup 
Enable direct signups for 5 minutes or so ;)

**Comment by chibill** [comment]
Working on figuring it out.

**Comment by wgaylord** [comment]
Well it seems there is no direct sign up setting... When I get home I can set something up.

**Comment by wgaylord** [comment]
Or just post your email then I will edit it out of the comment when I add you.

**Comment by iLexiconn** [comment]
Lol... It's not hard to guess though ;)
REMOVED

**Comment by wgaylord** [comment]
Okay done. Also sent it to everyone else.
